name: pull_request

# Run on pull requests that reference main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run python checks
        run: |
          pip install atlassian-python-api
          python build/build.py
  terraform:
    runs-on: ubuntu-latest
    env:
      OKTA_ORG_NAME: ${{ secrets.OKTA_ORG_NAME }}
      OKTA_BASE_URL: ${{ secrets.OKTA_BASE_URL }}
      OKTA_API_TOKEN: ${{ secrets.OKTA_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.CP_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CP_AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Debug commands # Feel free to add debug commands here
        run: |
          echo ">> pwd"
          pwd
          echo ">> ls"
          ls
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
      - name: Verify Terraform Installation
        run: |
          which terraform
          terraform --version
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan